# 제외할 폴더
excluded:
  - Tile2048UITests

# 줄 길이 제한
line_length:
  warning: 120
  error: 200

# 파일 길이 제한
file_length:
  warning: 400
  error: 1000
  
# 함수 길이 제한
function_body_length:
  warning: 40
  error: 100

# 타입(클래스, 구조체) 길이 제한
type_body_length:
  warning: 200
  error: 400

# 변수명 길이
identifier_name:
  min_length: 2
  max_length: 40

# 출력 형식
reporter: "xcode"
